"""update_evaluate_2

Revision ID: 184999b793dc
Revises: de54a9c79c3c
Create Date: 2025-05-23 13:23:13.840761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '184999b793dc'
down_revision: Union[str, None] = 'de54a9c79c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('product_variant_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'evaluate', 'product_variant', ['product_variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluate', type_='foreignkey')
    op.drop_column('evaluate', 'product_variant_id')
    # ### end Alembic commands ###
