"""update_evaluate_4

Revision ID: 4260c1b37624
Revises: 728d247bcfdf
Create Date: 2025-05-23 16:24:37.542646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4260c1b37624'
down_revision: Union[str, None] = '728d247bcfdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_column('evaluate', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('evaluate', 'image')
    # ### end Alembic commands ###
