"""update table Notification

Revision ID: 052c6a1ab829
Revises: d0e6888859c2
Create Date: 2025-09-11 18:32:22.325057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '052c6a1ab829'
down_revision: Union[str, None] = 'd0e6888859c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('action_type', sa.VARCHAR(), nullable=True))
    op.add_column('notification', sa.Column('action_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('notification', sa.Column('is_processed', sa.BOOLEAN(), server_default='false', nullable=False))
    op.add_column('notification', sa.Column('processed_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'processed_at')
    op.drop_column('notification', 'is_processed')
    op.drop_column('notification', 'action_data')
    op.drop_column('notification', 'action_type')
    # ### end Alembic commands ###
