"""add table UserSpecialOffer

Revision ID: 099b7530f267
Revises: 18867a7907b5
Create Date: 2025-08-29 12:58:06.965984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '099b7530f267'
down_revision: Union[str, None] = '18867a7907b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_special_offer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('special_offer_id', sa.Uuid(), nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['special_offer_id'], ['special_offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cart', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_price', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_table('user_special_offer')
    # ### end Alembic commands ###
