"""add returned_quantity to GoodsReceiptDetail

Revision ID: 0af2dd54531e
Revises: 68b406e0aa5f
Create Date: 2025-10-22 10:36:55.140132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0af2dd54531e'
down_revision: Union[str, None] = '68b406e0aa5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_detail', sa.Column('returned_quantity', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods_receipt_detail', 'returned_quantity')
    # ### end Alembic commands ###
