"""update GR and PR

Revision ID: 0b1e9a03e718
Revises: 0dced7fff05b
Create Date: 2025-10-14 20:52:16.493407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b1e9a03e718'
down_revision: Union[str, None] = '0dced7fff05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt', sa.Column('related_purchase_return_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'goods_receipt', 'purchase_return', ['related_purchase_return_id'], ['id'])
    op.add_column('goods_receipt_detail', sa.Column('related_return_detail_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'goods_receipt_detail', 'purchase_return_detail', ['related_return_detail_id'], ['id'])
    op.drop_column('purchase_return', 'refunded_amount')
    op.add_column('purchase_return_detail', sa.Column('rejection_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_return_detail', 'rejection_evidence')
    op.add_column('purchase_return', sa.Column('refunded_amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'goods_receipt_detail', type_='foreignkey')
    op.drop_column('goods_receipt_detail', 'related_return_detail_id')
    op.drop_constraint(None, 'goods_receipt', type_='foreignkey')
    op.drop_column('goods_receipt', 'related_purchase_return_id')
    # ### end Alembic commands ###
