"""change name Product to product_snapshot in Order_Detail

Revision ID: 0b3669fba714
Revises: 4c68a32c2fac
Create Date: 2025-09-16 16:34:50.812804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b3669fba714'
down_revision: Union[str, None] = '4c68a32c2fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('order_detail', 'Product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_detail', sa.Column('Product', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('order_detail', 'product_snapshot')
    # ### end Alembic commands ###
