"""add UniqueConstraint for Brand

Revision ID: 0da0c2b1135a
Revises: a9ca5df6dd3b
Create Date: 2025-09-23 12:26:41.766164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0da0c2b1135a'
down_revision: Union[str, None] = 'a9ca5df6dd3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('brand_name_key'), 'brand', type_='unique')
    op.drop_constraint(op.f('brand_slug_key'), 'brand', type_='unique')
    op.create_index('ix_brand_name_unique_not_deleted', 'brand', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_brand_slug_unique_not_deleted', 'brand', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_brand_slug_unique_not_deleted', table_name='brand', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_brand_name_unique_not_deleted', table_name='brand', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('brand_slug_key'), 'brand', ['slug'])
    op.create_unique_constraint(op.f('brand_name_key'), 'brand', ['name'])
    # ### end Alembic commands ###
