"""update supplier_invoice_urls in PO

Revision ID: 0dced7fff05b
Revises: d7a344f6c83b
Create Date: 2025-10-13 17:20:12.531282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dced7fff05b'
down_revision: Union[str, None] = 'd7a344f6c83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('supplier_invoice_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order', 'supplier_invoice_urls')
    # ### end Alembic commands ###
