"""update table OrderStatusHistory

Revision ID: 161e962f3fb2
Revises: 262789e7d75d
Create Date: 2025-09-03 14:52:19.502958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '161e962f3fb2'
down_revision: Union[str, None] = '262789e7d75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_status_history', 'note')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status_history', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
