"""update table cart and cart_item

Revision ID: 18867a7907b5
Revises: 05d4fa3258f1
Create Date: 2025-08-27 16:37:04.614311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '18867a7907b5'
down_revision: Union[str, None] = '05d4fa3258f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_special_offer_id_fkey'), 'cart', type_='foreignkey')
    op.drop_column('cart', 'discount')
    op.drop_column('cart', 'special_offer_id')
    op.drop_column('cart', 'sub_total')
    op.create_unique_constraint('uq_cart_item_cart_product_variant', 'cart_item', ['cart_id', 'product_id', 'product_variant_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_item_cart_product_variant', 'cart_item', type_='unique')
    op.add_column('cart', sa.Column('sub_total', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('cart', sa.Column('special_offer_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('cart', sa.Column('discount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cart_special_offer_id_fkey'), 'cart', 'special_offer', ['special_offer_id'], ['id'])
    # ### end Alembic commands ###
