"""add delivered_at to Order

Revision ID: 1c78ef2e0aa9
Revises: bc57bbd6974a
Create Date: 2025-09-13 21:21:56.113390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c78ef2e0aa9'
down_revision: Union[str, None] = 'bc57bbd6974a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivered_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivered_at')
    # ### end Alembic commands ###
