"""Add discount percent and offer snapshot to Order

Revision ID: 200fd6b7ff59
Revises: 1c78ef2e0aa9
Create Date: 2025-09-14 09:48:48.686084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '200fd6b7ff59'
down_revision: Union[str, None] = '1c78ef2e0aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('discount_percent', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('order', sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('order', sa.Column('special_offer_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('order', 'Address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('Address', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('order', 'special_offer_snapshot')
    op.drop_column('order', 'address_snapshot')
    op.drop_column('order', 'discount_percent')
    # ### end Alembic commands ###
