"""add UniqueConstraint for Material 2

Revision ID: 217d6c47766b
Revises: 598ee7d36fef
Create Date: 2025-09-23 12:43:45.843726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '217d6c47766b'
down_revision: Union[str, None] = '598ee7d36fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('material_name_key'), 'material', type_='unique')
    op.drop_constraint(op.f('material_slug_key'), 'material', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('material_slug_key'), 'material', ['slug'])
    op.create_unique_constraint(op.f('material_name_key'), 'material', ['name'])
    # ### end Alembic commands ###
