"""remove_warehouse_role

Revision ID: 2293cdadd718
Revises: c53d788963f0
Create Date: 2026-05-26 22:00:40.234045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2293cdadd718'
down_revision: Union[str, None] = 'c53d788963f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'warehouse_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('warehouse_role', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
