"""add avg_rating to product

Revision ID: 2299ca2bccd2
Revises: 641f1c7603fd
Create Date: 2025-08-21 10:52:52.077903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2299ca2bccd2'
down_revision: Union[str, None] = '641f1c7603fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('avg_rating', sa.FLOAT(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'avg_rating')
    # ### end Alembic commands ###
