"""update relationship Order and ReturnOrder

Revision ID: 22df2eeb0b8c
Revises: cb83dbe3665c
Create Date: 2025-09-16 09:14:03.236409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '22df2eeb0b8c'
down_revision: Union[str, None] = 'cb83dbe3665c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
