"""update CashTransaction, ReturnOrder, ReturnItem

Revision ID: 242af0411b4e
Revises: b77e358c256c
Create Date: 2025-12-25 22:13:19.327772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '242af0411b4e'
down_revision: Union[str, None] = 'b77e358c256c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cash_transaction', sa.Column('idempotency_key', sa.VARCHAR(length=100), nullable=True))
    op.add_column('cash_transaction', sa.Column('related_return_order_id', sa.UUID(), nullable=True))
    op.add_column('cash_transaction', sa.Column('related_order_id', sa.UUID(), nullable=True))
    op.add_column('cash_transaction', sa.Column('status', sa.VARCHAR(), server_default='completed', nullable=False))
    op.create_index(op.f('ix_cash_transaction_idempotency_key'), 'cash_transaction', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_cash_transaction_related_order_id'), 'cash_transaction', ['related_order_id'], unique=False)
    op.create_index(op.f('ix_cash_transaction_related_return_order_id'), 'cash_transaction', ['related_return_order_id'], unique=False)
    op.add_column('return_order', sa.Column('total_refund_amount', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('return_order', sa.Column('refunded_amount', sa.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_order', 'refunded_amount')
    op.drop_column('return_order', 'total_refund_amount')
    op.drop_index(op.f('ix_cash_transaction_related_return_order_id'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_related_order_id'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_idempotency_key'), table_name='cash_transaction')
    op.drop_column('cash_transaction', 'status')
    op.drop_column('cash_transaction', 'related_order_id')
    op.drop_column('cash_transaction', 'related_return_order_id')
    op.drop_column('cash_transaction', 'idempotency_key')
    # ### end Alembic commands ###
