"""add estimated_delivery_date to Order

Revision ID: 24cfe7509b25
Revises: 8c29b834bc73
Create Date: 2025-12-11 14:55:03.931277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24cfe7509b25'
down_revision: Union[str, None] = '8c29b834bc73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('estimated_delivery_date', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'estimated_delivery_date')
    # ### end Alembic commands ###
