"""add code to Province and Ward

Revision ID: 28e2ee71564a
Revises: fea596419438
Create Date: 2025-11-13 08:26:55.575559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '28e2ee71564a'
down_revision: Union[str, None] = 'fea596419438'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('province', sa.Column('code', sa.INTEGER(), nullable=False))
    op.add_column('ward', sa.Column('code', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ward', 'code')
    op.drop_column('province', 'code')
    # ### end Alembic commands ###
