"""add short description

Revision ID: 31d4a71cfff3
Revises: 6f2ff4a8e336
Create Date: 2025-08-25 14:51:31.302724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31d4a71cfff3'
down_revision: Union[str, None] = '6f2ff4a8e336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('short_description', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'short_description')
    # ### end Alembic commands ###
