"""add Setup2FAAttempt

Revision ID: 33adcc513c7f
Revises: 3ac2badfd230
Create Date: 2025-11-10 10:13:03.948299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '33adcc513c7f'
down_revision: Union[str, None] = '3ac2badfd230'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setup_2fa_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_id_attempted_at', 'setup_2fa_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_setup_2fa_attempts_attempted_at'), 'setup_2fa_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_setup_2fa_attempts_user_id'), 'setup_2fa_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_setup_2fa_attempts_user_id'), table_name='setup_2fa_attempts')
    op.drop_index(op.f('ix_setup_2fa_attempts_attempted_at'), table_name='setup_2fa_attempts')
    op.drop_index('idx_user_id_attempted_at', table_name='setup_2fa_attempts')
    op.drop_table('setup_2fa_attempts')
    # ### end Alembic commands ###
