"""add_special_offer_to_product

Revision ID: 38baf46a113e
Revises: e2616f79d24b
Create Date: 2025-07-23 18:35:47.120820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38baf46a113e'
down_revision: Union[str, None] = 'e2616f79d24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('special_offer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'product', 'special_offer', ['special_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'special_offer_id')
    # ### end Alembic commands ###
