"""add table payment_refund

Revision ID: 3bba1b132478
Revises: 7f63a4a41870
Create Date: 2025-09-10 08:26:00.503625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3bba1b132478'
down_revision: Union[str, None] = '7f63a4a41870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_refund',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('refund_type', sa.VARCHAR(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('refund_reason', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_no', sa.VARCHAR(), nullable=True),
    sa.Column('response_code', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('cancellation_reason', sa.VARCHAR(), nullable=True))
    op.add_column('order', sa.Column('cancellation_status', sa.VARCHAR(), nullable=True))
    op.add_column('order', sa.Column('cancellation_requested_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cancellation_requested_at')
    op.drop_column('order', 'cancellation_status')
    op.drop_column('order', 'cancellation_reason')
    op.drop_table('payment_refund')
    # ### end Alembic commands ###
