"""update foreign key GR

Revision ID: 3ef89c65176b
Revises: b115f752be73
Create Date: 2025-10-15 08:28:58.107726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ef89c65176b'
down_revision: Union[str, None] = 'b115f752be73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('goods_receipt_related_purchase_return_id_fkey'), 'goods_receipt', type_='foreignkey')
    op.drop_column('goods_receipt', 'related_purchase_return_id')
    op.drop_constraint(op.f('goods_receipt_detail_related_return_detail_id_fkey'), 'goods_receipt_detail', type_='foreignkey')
    op.drop_column('goods_receipt_detail', 'related_return_detail_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt_detail', sa.Column('related_return_detail_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('goods_receipt_detail_related_return_detail_id_fkey'), 'goods_receipt_detail', 'purchase_return_detail', ['related_return_detail_id'], ['id'])
    op.add_column('goods_receipt', sa.Column('related_purchase_return_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('goods_receipt_related_purchase_return_id_fkey'), 'goods_receipt', 'purchase_return', ['related_purchase_return_id'], ['id'])
    # ### end Alembic commands ###
