"""update table Payment

Revision ID: 4785fe00cebf
Revises: 052c6a1ab829
Create Date: 2025-09-12 14:36:48.895137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4785fe00cebf'
down_revision: Union[str, None] = '052c6a1ab829'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('txn_ref', sa.VARCHAR(), nullable=False))
    op.add_column('payment', sa.Column('bank_tran_no', sa.VARCHAR(), nullable=True))
    op.add_column('payment', sa.Column('bank_code', sa.VARCHAR(), nullable=True))
    op.add_column('payment', sa.Column('card_type', sa.VARCHAR(), nullable=True))
    op.add_column('payment', sa.Column('transaction_status', sa.VARCHAR(), nullable=True))
    op.add_column('payment', sa.Column('pay_date', postgresql.TIMESTAMP(), nullable=True))
    op.create_unique_constraint(None, 'payment', ['txn_ref'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'pay_date')
    op.drop_column('payment', 'transaction_status')
    op.drop_column('payment', 'card_type')
    op.drop_column('payment', 'bank_code')
    op.drop_column('payment', 'bank_tran_no')
    op.drop_column('payment', 'txn_ref')
    # ### end Alembic commands ###
