"""update images to ReturnItem

Revision ID: 4c68a32c2fac
Revises: 22df2eeb0b8c
Create Date: 2025-09-16 10:34:13.614967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4c68a32c2fac'
down_revision: Union[str, None] = '22df2eeb0b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_item', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('return_order', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('return_order', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('return_item', 'images')
    # ### end Alembic commands ###
