"""change otp_hash in User

Revision ID: 4db3ae57ead7
Revises: 3b307eb85ed3
Create Date: 2025-11-07 13:11:42.994754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4db3ae57ead7'
down_revision: Union[str, None] = '3b307eb85ed3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_hash', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'otp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'otp_hash')
    # ### end Alembic commands ###
