"""add UniqueConstraint for Tag

Revision ID: 525046703d81
Revises: 217d6c47766b
Create Date: 2025-09-23 13:00:57.368773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '525046703d81'
down_revision: Union[str, None] = '217d6c47766b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    op.drop_constraint(op.f('tag_name_key'), 'tag', type_='unique')
    op.drop_constraint(op.f('tag_slug_key'), 'tag', type_='unique')
    op.create_index('ix_tag_name_unique_not_deleted', 'tag', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_tag_slug_unique_not_deleted', 'tag', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_column('tag', 'usage_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index('ix_tag_slug_unique_not_deleted', table_name='tag', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tag_name_unique_not_deleted', table_name='tag', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('tag_slug_key'), 'tag', ['slug'])
    op.create_unique_constraint(op.f('tag_name_key'), 'tag', ['name'])
    op.drop_column('tag', 'products_count')
    # ### end Alembic commands ###
