"""update address for warehouse

Revision ID: 564fb5e30fc2
Revises: 2293cdadd718
Create Date: 2026-05-26 23:38:37.588932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '564fb5e30fc2'
down_revision: Union[str, None] = '2293cdadd718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('address_line', sa.VARCHAR(), nullable=False))
    op.add_column('warehouse', sa.Column('ward_id', sa.Uuid(), nullable=False))
    op.add_column('warehouse', sa.Column('province_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'warehouse', 'ward', ['ward_id'], ['id'])
    op.create_foreign_key(None, 'warehouse', 'province', ['province_id'], ['id'])
    op.drop_column('warehouse', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'province_id')
    op.drop_column('warehouse', 'ward_id')
    op.drop_column('warehouse', 'address_line')
    # ### end Alembic commands ###
