"""fix_product_variant_supabase

Revision ID: 57d6f7269ed2
Revises: ea5bc5731ea7
Create Date: 2026-05-25 21:01:20.756037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57d6f7269ed2'
down_revision: Union[str, None] = 'ea5bc5731ea7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('logo', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_brand_name_unique_not_deleted', 'brand', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_brand_slug_unique_not_deleted', 'brand', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('type_size', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('color',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_attempted_at', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('idx_ip_attempted_at', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_table('material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_name_unique_not_deleted', 'material', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_material_slug_unique_not_deleted', 'material', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('group', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_permission_code_unique_not_deleted', 'permission', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index(op.f('ix_permission_group'), 'permission', ['group'], unique=False)
    op.create_table('province',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code_name', sa.VARCHAR(), nullable=False),
    sa.Column('division_type', sa.VARCHAR(), nullable=False),
    sa.Column('phone_code', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_role_name_unique_not_deleted', 'role', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('size',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_type'), 'size', ['type'], unique=False)
    op.create_table('special_offer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('discount', sa.INTEGER(), nullable=False),
    sa.Column('condition', sa.INTEGER(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('total_quantity', sa.INTEGER(), nullable=False),
    sa.Column('scope', sa.VARCHAR(), server_default='order', nullable=False),
    sa.Column('used_quantity', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('start_time', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('bank_account', sa.VARCHAR(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), nullable=True),
    sa.Column('credit_limit', sa.INTEGER(), nullable=True),
    sa.Column('current_debt', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tag_name_unique_not_deleted', 'tag', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_tag_slug_unique_not_deleted', 'tag', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(), nullable=False),
    sa.Column('last_name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('customer_status', sa.VARCHAR(), server_default='active', nullable=False),
    sa.Column('staff_status', sa.VARCHAR(), server_default='active', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_customer', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('two_fa_secret', sa.VARCHAR(), nullable=True),
    sa.Column('two_fa_enabled', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=True),
    sa.Column('warehouse_role', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warehouse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cart',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_deleted_at', 'cart', ['deleted_at'], unique=False)
    op.create_index('ix_cart_user_deleted', 'cart', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_cart_user_id', 'cart', ['user_id'], unique=False)
    op.create_index('uq_cart_user_active', 'cart', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('cash_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_code', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_name', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('related_return_order_id', sa.UUID(), nullable=True),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='completed', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_code')
    )
    op.create_index(op.f('ix_cash_transaction_idempotency_key'), 'cash_transaction', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_cash_transaction_related_order_id'), 'cash_transaction', ['related_order_id'], unique=False)
    op.create_index(op.f('ix_cash_transaction_related_return_order_id'), 'cash_transaction', ['related_return_order_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('sub_total', sa.INTEGER(), nullable=False),
    sa.Column('total_price', sa.INTEGER(), nullable=False),
    sa.Column('discount', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('discount_percent', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), server_default='vnpay', nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('special_offer_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('estimated_delivery_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('address_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('special_offer_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cancellation_reason', sa.VARCHAR(), nullable=True),
    sa.Column('cancellation_status', sa.VARCHAR(), nullable=True),
    sa.Column('cancellation_requested_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['special_offer_id'], ['special_offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_verification_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_ip_attempted_at', 'otp_verification_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index('idx_otp_user_id_attempted_at', 'otp_verification_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_otp_verification_attempts_attempted_at'), 'otp_verification_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_otp_verification_attempts_user_id'), 'otp_verification_attempts', ['user_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('short_description', sa.TEXT(), nullable=True),
    sa.Column('popularity_score', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('total_sold', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('review_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('avg_rating', sa.FLOAT(), server_default='0', nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='active', nullable=False),
    sa.Column('slug', sa.VARCHAR(), nullable=True),
    sa.Column('special_offer_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('brand_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ),
    sa.ForeignKeyConstraint(['special_offer_id'], ['special_offer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sub_total', sa.INTEGER(), nullable=False),
    sa.Column('discount_amount', sa.INTEGER(), nullable=False),
    sa.Column('shipping_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(), server_default='unpaid', nullable=False),
    sa.Column('paid_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('supplier_invoice_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('role_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission_role_permission')
    )
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('setup_2fa_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_id_attempted_at', 'setup_2fa_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_setup_2fa_attempts_attempted_at'), 'setup_2fa_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_setup_2fa_attempts_user_id'), 'setup_2fa_attempts', ['user_id'], unique=False)
    op.create_table('stock_adjustment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_code', sa.VARCHAR(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('total_adjustment_value', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_code')
    )
    op.create_table('user_role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role_user_role')
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('user_special_offer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('special_offer_id', sa.Uuid(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['special_offer_id'], ['special_offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('special_offer_id', 'user_id', name='uq_user_special_offer_offer_user')
    )
    op.create_table('ward',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code_name', sa.VARCHAR(), nullable=False),
    sa.Column('short_code_name', sa.VARCHAR(), nullable=False),
    sa.Column('division_type', sa.VARCHAR(), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_code_name'), 'ward', ['code_name'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('line', sa.VARCHAR(), nullable=False),
    sa.Column('ward_id', sa.Uuid(), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.Column('district', sa.VARCHAR(), nullable=True),
    sa.Column('country', sa.VARCHAR(), server_default='Việt Nam', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories_product',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('categories_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['categories_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('parent_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('receipt_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('total_received_amount', sa.INTEGER(), nullable=False),
    sa.Column('delivery_note_number', sa.VARCHAR(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('inspected_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('has_discrepancy', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('discrepancy_notes', sa.TEXT(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('inspected_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('order_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payment_gateway', sa.VARCHAR(), nullable=False),
    sa.Column('txn_ref', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_no', sa.VARCHAR(), nullable=False),
    sa.Column('bank_tran_no', sa.VARCHAR(), nullable=True),
    sa.Column('bank_code', sa.VARCHAR(), nullable=True),
    sa.Column('card_type', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('order_info', sa.VARCHAR(), nullable=True),
    sa.Column('response_code', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_status', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='success', nullable=False),
    sa.Column('pay_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_ref')
    )
    op.create_table('product_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('material_id', sa.Uuid(), nullable=False),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_variant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('size', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('sku', sa.VARCHAR(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('color_id', sa.Uuid(), nullable=True),
    sa.Column('color_name', sa.VARCHAR(), nullable=True),
    sa.Column('color_code', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['color.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('total_refund_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('refunded_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('refunded_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_table('supplier_product',
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'product_id')
    )
    op.create_table('cart_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), server_default='1', nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_cart_item_price_positive'),
    sa.CheckConstraint('quantity > 0 AND quantity <= 999', name='ck_cart_item_quantity_range'),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='fk_cart_item_cart', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_item_cart_deleted', 'cart_item', ['cart_id', 'deleted_at'], unique=False)
    op.create_index('ix_cart_item_cart_id', 'cart_item', ['cart_id'], unique=False)
    op.create_index('ix_cart_item_deleted_at', 'cart_item', ['deleted_at'], unique=False)
    op.create_index('ix_cart_item_product_variant_id', 'cart_item', ['product_variant_id'], unique=False)
    op.create_index('ix_cart_item_variant_deleted', 'cart_item', ['product_variant_id', 'deleted_at'], unique=False)
    op.create_index('uq_cart_item_cart_variant_active', 'cart_item', ['cart_id', 'product_variant_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('sender_type', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('special_offer_id', sa.Uuid(), nullable=True),
    sa.Column('return_order_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('action_type', sa.VARCHAR(), nullable=True),
    sa.Column('action_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_order.id'], ),
    sa.ForeignKeyConstraint(['special_offer_id'], ['special_offer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_refund',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('refund_type', sa.VARCHAR(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('refund_reason', sa.VARCHAR(), nullable=True),
    sa.Column('txn_ref', sa.VARCHAR(), nullable=True),
    sa.Column('bank_code', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_no', sa.VARCHAR(), nullable=True),
    sa.Column('transaction_status', sa.VARCHAR(), nullable=True),
    sa.Column('response_code', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('attempt_count', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_order_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('received_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_return',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('return_type', sa.VARCHAR(), server_default='return_to_supplier', nullable=False),
    sa.Column('return_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('shipped_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('total_return_amount', sa.INTEGER(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('return_reason', sa.TEXT(), nullable=False),
    sa.Column('delivery_note_number', sa.VARCHAR(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('completed_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['completed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_table('stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('reserved_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('min_stock_level', sa.INTEGER(), nullable=True),
    sa.Column('max_stock_level', sa.INTEGER(), nullable=True),
    sa.Column('cost_price', sa.INTEGER(), nullable=True),
    sa.Column('last_cost_price', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='available', nullable=False),
    sa.Column('last_inbound_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_outbound_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_variant_id', name='uq_stock_warehouse_product_variant')
    )
    op.create_table('stock_adjustment_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_adjustment_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('system_quantity', sa.INTEGER(), nullable=False),
    sa.Column('actual_quantity', sa.INTEGER(), nullable=False),
    sa.Column('difference_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=True),
    sa.Column('adjustment_value', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['stock_adjustment_id'], ['stock_adjustment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_reservation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='active', nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('rate', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.VARCHAR(), nullable=True),
    sa.Column('additional_comment', sa.VARCHAR(), nullable=True),
    sa.Column('additional_image', sa.VARCHAR(), nullable=True),
    sa.Column('additional_created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('seller_reply', sa.TEXT(), nullable=True),
    sa.Column('seller_reply_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('order_detail_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_detail_id'], ['order_detail.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_detail_id'),
    sa.UniqueConstraint('order_detail_id', name='uq_evaluate_order_detail_id')
    )
    op.create_table('goods_receipt_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('po_detail_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.INTEGER(), nullable=False),
    sa.Column('received_quantity', sa.INTEGER(), nullable=False),
    sa.Column('accepted_quantity', sa.INTEGER(), nullable=False),
    sa.Column('rejected_quantity', sa.INTEGER(), nullable=False),
    sa.Column('returned_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_detail.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_order_id', sa.Uuid(), nullable=False),
    sa.Column('order_detail_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_detail_id'], ['order_detail.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('previous_quantity', sa.INTEGER(), nullable=False),
    sa.Column('new_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=True),
    sa.Column('total_cost', sa.INTEGER(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_return_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_return_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_detail_id', sa.Uuid(), nullable=True),
    sa.Column('return_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rejection_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_detail_id'], ['goods_receipt_detail.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_return_detail')
    op.drop_table('stock_transaction')
    op.drop_table('return_item')
    op.drop_table('goods_receipt_detail')
    op.drop_table('evaluate')
    op.drop_table('stock_reservation')
    op.drop_table('stock_adjustment_item')
    op.drop_table('stock')
    op.drop_table('purchase_return')
    op.drop_table('purchase_order_detail')
    op.drop_table('payment_refund')
    op.drop_table('order_detail')
    op.drop_table('notification')
    op.drop_index('uq_cart_item_cart_variant_active', table_name='cart_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_cart_item_variant_deleted', table_name='cart_item')
    op.drop_index('ix_cart_item_product_variant_id', table_name='cart_item')
    op.drop_index('ix_cart_item_deleted_at', table_name='cart_item')
    op.drop_index('ix_cart_item_cart_id', table_name='cart_item')
    op.drop_index('ix_cart_item_cart_deleted', table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_table('supplier_product')
    op.drop_table('supplier_payment')
    op.drop_table('return_order')
    op.drop_table('product_variant')
    op.drop_table('product_tag')
    op.drop_table('product_material')
    op.drop_table('payment')
    op.drop_table('order_status_history')
    op.drop_table('goods_receipt')
    op.drop_table('categories_product')
    op.drop_table('address')
    op.drop_index(op.f('ix_ward_code_name'), table_name='ward')
    op.drop_table('ward')
    op.drop_table('user_special_offer')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_table('stock_adjustment')
    op.drop_index(op.f('ix_setup_2fa_attempts_user_id'), table_name='setup_2fa_attempts')
    op.drop_index(op.f('ix_setup_2fa_attempts_attempted_at'), table_name='setup_2fa_attempts')
    op.drop_index('idx_user_id_attempted_at', table_name='setup_2fa_attempts')
    op.drop_table('setup_2fa_attempts')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_table('purchase_order')
    op.drop_table('product')
    op.drop_index(op.f('ix_otp_verification_attempts_user_id'), table_name='otp_verification_attempts')
    op.drop_index(op.f('ix_otp_verification_attempts_attempted_at'), table_name='otp_verification_attempts')
    op.drop_index('idx_otp_user_id_attempted_at', table_name='otp_verification_attempts')
    op.drop_index('idx_otp_ip_attempted_at', table_name='otp_verification_attempts')
    op.drop_table('otp_verification_attempts')
    op.drop_table('order')
    op.drop_index(op.f('ix_cash_transaction_related_return_order_id'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_related_order_id'), table_name='cash_transaction')
    op.drop_index(op.f('ix_cash_transaction_idempotency_key'), table_name='cash_transaction')
    op.drop_table('cash_transaction')
    op.drop_index('uq_cart_user_active', table_name='cart', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_cart_user_id', table_name='cart')
    op.drop_index('ix_cart_user_deleted', table_name='cart')
    op.drop_index('ix_cart_deleted_at', table_name='cart')
    op.drop_table('cart')
    op.drop_table('warehouse')
    op.drop_table('user')
    op.drop_index('ix_tag_slug_unique_not_deleted', table_name='tag', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_tag_name_unique_not_deleted', table_name='tag', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('tag')
    op.drop_table('supplier')
    op.drop_table('special_offer')
    op.drop_index(op.f('ix_size_type'), table_name='size')
    op.drop_table('size')
    op.drop_index('ix_role_name_unique_not_deleted', table_name='role', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('role')
    op.drop_table('province')
    op.drop_index(op.f('ix_permission_group'), table_name='permission')
    op.drop_index('ix_permission_code_unique_not_deleted', table_name='permission', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('permission')
    op.drop_index('ix_material_slug_unique_not_deleted', table_name='material', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_material_name_unique_not_deleted', table_name='material', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('material')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index('idx_ip_attempted_at', table_name='login_attempts')
    op.drop_index('idx_email_attempted_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_table('color')
    op.drop_table('categories')
    op.drop_index('ix_brand_slug_unique_not_deleted', table_name='brand', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_brand_name_unique_not_deleted', table_name='brand', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('brand')
    # ### end Alembic commands ###
