"""add total_sold and scope

Revision ID: 57fccc2050cb
Revises: 2299ca2bccd2
Create Date: 2025-08-22 09:17:10.536475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '57fccc2050cb'
down_revision: Union[str, None] = '2299ca2bccd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('total_sold', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('special_offer', sa.Column('scope', sa.VARCHAR(), server_default='order', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('special_offer', 'scope')
    op.drop_column('product', 'total_sold')
    # ### end Alembic commands ###
