"""add UniqueConstraint for Material

Revision ID: 598ee7d36fef
Revises: 0da0c2b1135a
Create Date: 2025-09-23 12:38:05.061228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '598ee7d36fef'
down_revision: Union[str, None] = '0da0c2b1135a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_material_name_unique_not_deleted', 'material', ['name'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_material_slug_unique_not_deleted', 'material', ['slug'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_material_slug_unique_not_deleted', table_name='material', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_material_name_unique_not_deleted', table_name='material', postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###
