"""update popularity_score for product

Revision ID: 641f1c7603fd
Revises: f26dffccc95f
Create Date: 2025-08-19 09:34:11.156262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '641f1c7603fd'
down_revision: Union[str, None] = 'f26dffccc95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('popularity_score', sa.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'popularity_score')
    # ### end Alembic commands ###
