"""add parent_receipt_id

Revision ID: 68b406e0aa5f
Revises: 3ef89c65176b
Create Date: 2025-10-15 15:21:59.041821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68b406e0aa5f'
down_revision: Union[str, None] = '3ef89c65176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt', sa.Column('parent_receipt_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'goods_receipt', 'goods_receipt', ['parent_receipt_id'], ['id'])
    op.drop_column('goods_receipt', 'invoice_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods_receipt', sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'goods_receipt', type_='foreignkey')
    op.drop_column('goods_receipt', 'parent_receipt_id')
    # ### end Alembic commands ###
