"""add usage_count to Tag

Revision ID: 6d2f4b973474
Revises: df64eefe4df0
Create Date: 2025-09-22 11:19:08.131307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d2f4b973474'
down_revision: Union[str, None] = 'df64eefe4df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('usage_count', sa.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'usage_count')
    # ### end Alembic commands ###
