"""update column for UserSpecialOffer

Revision ID: 6f333e60e520
Revises: 53f8726d446a
Create Date: 2025-08-29 16:29:24.402055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f333e60e520'
down_revision: Union[str, None] = '53f8726d446a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_special_offer', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('user_special_offer', sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_special_offer', 'deleted_at')
    op.drop_column('user_special_offer', 'updated_at')
    # ### end Alembic commands ###
