"""update_evaluate_3

Revision ID: 728d247bcfdf
Revises: 184999b793dc
Create Date: 2025-05-23 13:37:16.499263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '728d247bcfdf'
down_revision: Union[str, None] = '184999b793dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'evaluate', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluate', type_='foreignkey')
    op.drop_column('evaluate', 'user_id')
    # ### end Alembic commands ###
