"""update table UserSpecialOffer 2

Revision ID: 795fdaed0071
Revises: 1a231677db97
Create Date: 2025-08-29 13:09:40.559326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '795fdaed0071'
down_revision: Union[str, None] = '1a231677db97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_special_offer', 'user_special_offer', ['user_id', 'special_offer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_special_offer', 'user_special_offer', type_='unique')
    # ### end Alembic commands ###
