"""update table UserSpecialOffer 3

Revision ID: 7ab74bf32885
Revises: 795fdaed0071
Create Date: 2025-08-29 13:11:34.610012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ab74bf32885'
down_revision: Union[str, None] = '795fdaed0071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_special_offer', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user_special_offer', sa.Column('used_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_special_offer', 'used_at')
    op.drop_column('user_special_offer', 'created_at')
    # ### end Alembic commands ###
