"""add products_count to Brand

Revision ID: 7ea044c410eb
Revises: 6d2f4b973474
Create Date: 2025-09-23 08:29:59.405314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7ea044c410eb'
down_revision: Union[str, None] = '6d2f4b973474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand', 'products_count')
    # ### end Alembic commands ###
