"""add complete field to PurchaseReturn

Revision ID: 7f04f92eecc4
Revises: 9015b9bca4a4
Create Date: 2025-10-23 20:44:18.705970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f04f92eecc4'
down_revision: Union[str, None] = '9015b9bca4a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_return', sa.Column('completed_by', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'purchase_return', 'user', ['completed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_return', type_='foreignkey')
    op.drop_column('purchase_return', 'completed_by')
    # ### end Alembic commands ###
