"""add special_offer_id to Order

Revision ID: 7f63a4a41870
Revises: e9463589be13
Create Date: 2025-09-09 09:43:23.533859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7f63a4a41870'
down_revision: Union[str, None] = 'e9463589be13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('special_offer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'order', 'special_offer', ['special_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'special_offer_id')
    # ### end Alembic commands ###
