"""update terms PO

Revision ID: 8550bba40a3b
Revises: 8a2e31b6cb8a
Create Date: 2025-10-08 17:53:38.115126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8550bba40a3b'
down_revision: Union[str, None] = '8a2e31b6cb8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_order', sa.Column('applied_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('purchase_order', sa.Column('is_partial_delivery', sa.BOOLEAN(), server_default='false', nullable=False))
    op.add_column('purchase_order', sa.Column('total_delivery_batches', sa.INTEGER(), server_default='1', nullable=False))
    op.add_column('purchase_order', sa.Column('completed_delivery_batches', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('purchase_order', sa.Column('original_payment_due_date', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('purchase_order', sa.Column('extended_payment_due_date', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('purchase_order', 'payment_terms')
    op.drop_column('purchase_order_detail', 'original_payment_due_date')
    op.drop_column('purchase_order_detail', 'extended_payment_due_date')
    op.drop_column('purchase_order_detail', 'is_partial_delivery')
    op.drop_column('purchase_order_detail', 'completed_delivery_batches')
    op.drop_column('purchase_order_detail', 'total_delivery_batches')
    op.add_column('supplier', sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('supplier', 'payment_terms')
    op.drop_column('supplier', 'credit_limit')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('credit_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('supplier', sa.Column('payment_terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('supplier', 'terms')
    op.add_column('purchase_order_detail', sa.Column('total_delivery_batches', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('purchase_order_detail', sa.Column('completed_delivery_batches', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('purchase_order_detail', sa.Column('is_partial_delivery', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('purchase_order_detail', sa.Column('extended_payment_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('purchase_order_detail', sa.Column('original_payment_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('purchase_order', sa.Column('payment_terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('purchase_order', 'extended_payment_due_date')
    op.drop_column('purchase_order', 'original_payment_due_date')
    op.drop_column('purchase_order', 'completed_delivery_batches')
    op.drop_column('purchase_order', 'total_delivery_batches')
    op.drop_column('purchase_order', 'is_partial_delivery')
    op.drop_column('purchase_order', 'applied_terms')
    # ### end Alembic commands ###
