"""add table for inventory management

Revision ID: 86db7a43ded8
Revises: 525046703d81
Create Date: 2025-09-28 19:46:21.962803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86db7a43ded8'
down_revision: Union[str, None] = '525046703d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('address', sa.TEXT(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('manager_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('is_default', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stock_adjustment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adjustment_code', sa.VARCHAR(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('total_adjustment_value', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('applied_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adjustment_code')
    )
    op.create_table('stock_transfer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transfer_code', sa.VARCHAR(), nullable=False),
    sa.Column('from_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('to_warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('shipped_by', sa.Uuid(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('shipped_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['warehouse.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['shipped_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_code')
    )
    op.create_table('stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('reserved_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('available_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('min_stock_level', sa.INTEGER(), nullable=True),
    sa.Column('max_stock_level', sa.INTEGER(), nullable=True),
    sa.Column('cost_price', sa.INTEGER(), nullable=True),
    sa.Column('last_cost_price', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='available', nullable=False),
    sa.Column('last_inbound_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('last_outbound_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('warehouse_id', 'product_variant_id', name='uq_stock_warehouse_product_variant')
    )
    op.create_table('stock_adjustment_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_adjustment_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('system_quantity', sa.INTEGER(), nullable=False),
    sa.Column('actual_quantity', sa.INTEGER(), nullable=False),
    sa.Column('difference_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=True),
    sa.Column('adjustment_value', sa.INTEGER(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['stock_adjustment_id'], ['stock_adjustment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_reservation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='active', nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transfer_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_transfer_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('requested_quantity', sa.INTEGER(), nullable=False),
    sa.Column('shipped_quantity', sa.INTEGER(), nullable=True),
    sa.Column('received_quantity', sa.INTEGER(), nullable=True),
    sa.Column('unit_cost', sa.INTEGER(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['stock_transfer_id'], ['stock_transfer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('stock_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('previous_quantity', sa.INTEGER(), nullable=False),
    sa.Column('new_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=True),
    sa.Column('total_cost', sa.INTEGER(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('staff_status', sa.VARCHAR(), server_default='active', nullable=False))
    op.add_column('user', sa.Column('is_staff', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_staff')
    op.drop_column('user', 'staff_status')
    op.drop_table('stock_transaction')
    op.drop_table('stock_transfer_item')
    op.drop_table('stock_reservation')
    op.drop_table('stock_adjustment_item')
    op.drop_table('stock')
    op.drop_table('stock_transfer')
    op.drop_table('stock_adjustment')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
