"""Add partialdelivery table and update other tables

Revision ID: 8a2e31b6cb8a
Revises: 9b69786ff386
Create Date: 2025-10-08 17:21:40.821964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a2e31b6cb8a'
down_revision: Union[str, None] = '9b69786ff386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partial_delivery_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('delivery_batch_number', sa.INTEGER(), nullable=False),
    sa.Column('proposed_quantity', sa.INTEGER(), nullable=False),
    sa.Column('proposed_amount', sa.INTEGER(), nullable=False),
    sa.Column('proposed_delivery_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('proposed_payment_extension_days', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('actual_delivery_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('actual_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('actual_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partial_delivery_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('po_detail_id', sa.Uuid(), nullable=False),
    sa.Column('proposed_quantity', sa.INTEGER(), nullable=False),
    sa.Column('actual_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_detail.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['partial_delivery_schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('penalty_code', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('partial_delivery_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_payment_id', sa.Uuid(), nullable=True),
    sa.Column('violation_type', sa.VARCHAR(), nullable=False),
    sa.Column('violated_by', sa.VARCHAR(), nullable=False),
    sa.Column('violation_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('expected_value', sa.VARCHAR(), nullable=False),
    sa.Column('actual_value', sa.VARCHAR(), nullable=False),
    sa.Column('difference_value', sa.INTEGER(), nullable=False),
    sa.Column('difference_unit', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='recorded', nullable=False),
    sa.Column('resolution_notes', sa.TEXT(), nullable=True),
    sa.Column('agreed_compensation_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['partial_delivery_schedule_id'], ['partial_delivery_schedule.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payment.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('penalty_code')
    )
    op.add_column('goods_receipt', sa.Column('is_partial_delivery_batch', sa.BOOLEAN(), server_default='false', nullable=False))
    op.add_column('goods_receipt', sa.Column('delivery_batch_number', sa.INTEGER(), nullable=True))
    op.add_column('purchase_order_detail', sa.Column('is_partial_delivery', sa.BOOLEAN(), server_default='false', nullable=False))
    op.add_column('purchase_order_detail', sa.Column('total_delivery_batches', sa.INTEGER(), server_default='1', nullable=False))
    op.add_column('purchase_order_detail', sa.Column('completed_delivery_batches', sa.INTEGER(), server_default='0', nullable=False))
    op.add_column('purchase_order_detail', sa.Column('original_payment_due_date', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('purchase_order_detail', sa.Column('extended_payment_due_date', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_order_detail', 'extended_payment_due_date')
    op.drop_column('purchase_order_detail', 'original_payment_due_date')
    op.drop_column('purchase_order_detail', 'completed_delivery_batches')
    op.drop_column('purchase_order_detail', 'total_delivery_batches')
    op.drop_column('purchase_order_detail', 'is_partial_delivery')
    op.drop_column('goods_receipt', 'delivery_batch_number')
    op.drop_column('goods_receipt', 'is_partial_delivery_batch')
    op.drop_table('penalty_record')
    op.drop_table('partial_delivery_detail')
    op.drop_table('partial_delivery_schedule')
    # ### end Alembic commands ###
