"""implement cart model

Revision ID: 8c29b834bc73
Revises: 28e2ee71564a
Create Date: 2025-12-08 10:42:44.491793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c29b834bc73'
down_revision: Union[str, None] = '28e2ee71564a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cart_deleted_at', 'cart', ['deleted_at'], unique=False)
    op.create_index('ix_cart_user_deleted', 'cart', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_cart_user_id', 'cart', ['user_id'], unique=False)
    op.create_index('uq_cart_user_active', 'cart', ['user_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_constraint(op.f('uq_cart_item_cart_product_variant'), 'cart_item', type_='unique')
    op.create_index('ix_cart_item_cart_deleted', 'cart_item', ['cart_id', 'deleted_at'], unique=False)
    op.create_index('ix_cart_item_cart_id', 'cart_item', ['cart_id'], unique=False)
    op.create_index('ix_cart_item_deleted_at', 'cart_item', ['deleted_at'], unique=False)
    op.create_index('ix_cart_item_product_variant_id', 'cart_item', ['product_variant_id'], unique=False)
    op.create_index('ix_cart_item_variant_deleted', 'cart_item', ['product_variant_id', 'deleted_at'], unique=False)
    op.create_index('uq_cart_item_cart_variant_active', 'cart_item', ['cart_id', 'product_variant_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_foreign_key('fk_cart_item_cart', 'cart_item', 'cart', ['cart_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cart_item_cart', 'cart_item', type_='foreignkey')
    op.drop_index('uq_cart_item_cart_variant_active', table_name='cart_item', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_cart_item_variant_deleted', table_name='cart_item')
    op.drop_index('ix_cart_item_product_variant_id', table_name='cart_item')
    op.drop_index('ix_cart_item_deleted_at', table_name='cart_item')
    op.drop_index('ix_cart_item_cart_id', table_name='cart_item')
    op.drop_index('ix_cart_item_cart_deleted', table_name='cart_item')
    op.create_unique_constraint(op.f('uq_cart_item_cart_product_variant'), 'cart_item', ['cart_id', 'product_id', 'product_variant_id'])
    op.drop_index('uq_cart_user_active', table_name='cart', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_cart_user_id', table_name='cart')
    op.drop_index('ix_cart_user_deleted', table_name='cart')
    op.drop_index('ix_cart_deleted_at', table_name='cart')
    # ### end Alembic commands ###
