"""add confirmed field to PurchaseReturn

Revision ID: 9015b9bca4a4
Revises: 0af2dd54531e
Create Date: 2025-10-23 11:28:34.639518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9015b9bca4a4'
down_revision: Union[str, None] = '0af2dd54531e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_return', sa.Column('confirmed_by', sa.Uuid(), nullable=True))
    op.add_column('purchase_return', sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True))
    op.create_foreign_key(None, 'purchase_return', 'user', ['confirmed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_return', type_='foreignkey')
    op.drop_column('purchase_return', 'confirmed_at')
    op.drop_column('purchase_return', 'confirmed_by')
    # ### end Alembic commands ###
