"""Update table notification and special offer

Revision ID: 920fb52d366d
Revises: a5cd0636608d
Create Date: 2025-09-13 12:03:03.144777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '920fb52d366d'
down_revision: Union[str, None] = 'a5cd0636608d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('special_offer_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'notification', 'special_offer', ['special_offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'special_offer_id')
    # ### end Alembic commands ###
