"""add index to size

Revision ID: 932d8ac1870c
Revises: cbff3ed53614
Create Date: 2025-08-16 11:09:17.881691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '932d8ac1870c'
down_revision: Union[str, None] = 'cbff3ed53614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_size_type'), 'size', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_size_type'), table_name='size')
    # ### end Alembic commands ###
