"""Add payment and update order

Revision ID: 9b389cd1a8f2
Revises: 40381b1c2851
Create Date: 2025-09-06 10:39:27.883066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b389cd1a8f2'
down_revision: Union[str, None] = '40381b1c2851'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('payment_gateway', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_no', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('response_code', sa.VARCHAR(), nullable=True),
    sa.Column('order_info', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='success', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('order', sa.Column('payment_status', sa.VARCHAR(), server_default='pending', nullable=False))
    op.drop_column('order', 'transaction_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('transaction_no', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('order', 'payment_status')
    op.drop_table('payment')
    # ### end Alembic commands ###
