"""Add inventory management table

Revision ID: 9b69786ff386
Revises: 9e3c730f6e0f
Create Date: 2025-10-06 08:00:16.789249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b69786ff386'
down_revision: Union[str, None] = '9e3c730f6e0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('contact_person', sa.VARCHAR(), nullable=True),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('bank_account', sa.VARCHAR(), nullable=True),
    sa.Column('bank_name', sa.VARCHAR(), nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(), nullable=True),
    sa.Column('credit_limit', sa.INTEGER(), nullable=True),
    sa.Column('current_debt', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default='true', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('po_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('order_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('expected_delivery_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sub_total', sa.INTEGER(), nullable=False),
    sa.Column('discount_amount', sa.INTEGER(), nullable=False),
    sa.Column('shipping_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_terms', sa.VARCHAR(), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(), server_default='unpaid', nullable=False),
    sa.Column('paid_amount', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('sent_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('confirmed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('cancelled_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('cancellation_reason', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number')
    )
    op.create_table('goods_receipt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_number', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('receipt_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('total_received_amount', sa.INTEGER(), nullable=False),
    sa.Column('invoice_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('delivery_note_number', sa.VARCHAR(), nullable=True),
    sa.Column('received_by', sa.Uuid(), nullable=True),
    sa.Column('inspected_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('has_discrepancy', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('discrepancy_notes', sa.TEXT(), nullable=True),
    sa.Column('quality_check_passed', sa.BOOLEAN(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('inspected_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inspected_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['received_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_number')
    )
    op.create_table('supplier_payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_number', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('payment_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('reference_number', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_table('purchase_order_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('received_quantity', sa.INTEGER(), server_default='0', nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goods_receipt_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('po_detail_id', sa.Uuid(), nullable=False),
    sa.Column('ordered_quantity', sa.INTEGER(), nullable=False),
    sa.Column('received_quantity', sa.INTEGER(), nullable=False),
    sa.Column('accepted_quantity', sa.INTEGER(), nullable=False),
    sa.Column('rejected_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('quality_status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.TEXT(), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_detail.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goods_receipt_detail')
    op.drop_table('purchase_order_detail')
    op.drop_table('supplier_payment')
    op.drop_table('goods_receipt')
    op.drop_table('purchase_order')
    op.drop_table('supplier')
    # ### end Alembic commands ###
