"""Add staff and manager to Warehouse

Revision ID: 9e3c730f6e0f
Revises: b96f37c52e6b
Create Date: 2025-10-01 10:05:42.139533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9e3c730f6e0f'
down_revision: Union[str, None] = 'b96f37c52e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('warehouse_id', sa.Uuid(), nullable=True))
    op.add_column('user', sa.Column('warehouse_role', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'user', 'warehouse', ['warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'warehouse_role')
    op.drop_column('user', 'warehouse_id')
    # ### end Alembic commands ###
