"""remove percentage from product_material

Revision ID: 9f0c2ed66fa6
Revises: 564fb5e30fc2
Create Date: 2026-06-03 16:58:15.611602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f0c2ed66fa6'
down_revision: Union[str, None] = '564fb5e30fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_material', 'percentage')
    op.add_column('warehouse', sa.Column('address_line', sa.VARCHAR(), nullable=False))
    op.add_column('warehouse', sa.Column('ward_id', sa.Uuid(), nullable=False))
    op.add_column('warehouse', sa.Column('province_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'warehouse', 'ward', ['ward_id'], ['id'])
    op.create_foreign_key(None, 'warehouse', 'province', ['province_id'], ['id'])
    op.drop_column('warehouse', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'province_id')
    op.drop_column('warehouse', 'ward_id')
    op.drop_column('warehouse', 'address_line')
    op.add_column('product_material', sa.Column('percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
