"""update table PaymentRefund

Revision ID: a5cd0636608d
Revises: 4785fe00cebf
Create Date: 2025-09-12 15:48:53.087333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5cd0636608d'
down_revision: Union[str, None] = '4785fe00cebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_refund', sa.Column('txn_ref', sa.VARCHAR(), nullable=True))
    op.add_column('payment_refund', sa.Column('bank_code', sa.VARCHAR(), nullable=True))
    op.add_column('payment_refund', sa.Column('transaction_status', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_refund', 'transaction_status')
    op.drop_column('payment_refund', 'bank_code')
    op.drop_column('payment_refund', 'txn_ref')
    # ### end Alembic commands ###
