"""add products_count to Material

Revision ID: a9ca5df6dd3b
Revises: 7ea044c410eb
Create Date: 2025-09-23 09:01:02.693917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a9ca5df6dd3b'
down_revision: Union[str, None] = '7ea044c410eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('products_count', sa.INTEGER(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'products_count')
    # ### end Alembic commands ###
