"""update_evaluate_order_1

Revision ID: abceab5abe3a
Revises: 4251e9879f62
Create Date: 2025-05-26 16:12:11.160723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abceab5abe3a'
down_revision: Union[str, None] = '4251e9879f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_evaluate_order_detail_id', 'evaluate', ['order_detail_id'])
    op.create_unique_constraint(None, 'evaluate', ['order_detail_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'evaluate', type_='unique')
    op.drop_constraint('uq_evaluate_order_detail_id', 'evaluate', type_='unique')
    # ### end Alembic commands ###
