"""update payment refund

Revision ID: ac3b380cd8e7
Revises: 200fd6b7ff59
Create Date: 2025-09-14 12:02:02.502060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac3b380cd8e7'
down_revision: Union[str, None] = '200fd6b7ff59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('received_at', postgresql.TIMESTAMP(), nullable=True))
    op.add_column('payment_refund', sa.Column('note', sa.VARCHAR(), nullable=True))
    op.add_column('return_order', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('return_order', 'images')
    op.drop_column('payment_refund', 'note')
    op.drop_column('order', 'received_at')
    # ### end Alembic commands ###
