"""add CashTransaction

Revision ID: b115f752be73
Revises: 0b1e9a03e718
Create Date: 2025-10-14 21:38:03.628561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b115f752be73'
down_revision: Union[str, None] = '0b1e9a03e718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_transaction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_code', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('transaction_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('reference_type', sa.VARCHAR(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('reference_name', sa.VARCHAR(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('performed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cash_transaction')
    # ### end Alembic commands ###
