"""add unique for UserSpecialOffer

Revision ID: b77e358c256c
Revises: 24cfe7509b25
Create Date: 2025-12-18 15:12:15.156037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b77e358c256c'
down_revision: Union[str, None] = '24cfe7509b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_special_offer_offer_user', 'user_special_offer', ['special_offer_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_special_offer_offer_user', 'user_special_offer', type_='unique')
    # ### end Alembic commands ###
