"""update manager_id and relationship to Warehouse

Revision ID: b96f37c52e6b
Revises: c9aafb371908
Create Date: 2025-10-01 09:07:27.634730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b96f37c52e6b'
down_revision: Union[str, None] = 'c9aafb371908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('manager_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'warehouse', 'user', ['manager_id'], ['id'])
    op.drop_column('warehouse', 'manager_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouse', sa.Column('manager_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'warehouse', type_='foreignkey')
    op.drop_column('warehouse', 'manager_id')
    # ### end Alembic commands ###
