"""Update table return order and return item

Revision ID: bc57bbd6974a
Revises: 920fb52d366d
Create Date: 2025-09-13 21:03:06.930731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc57bbd6974a'
down_revision: Union[str, None] = '920fb52d366d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='pending', nullable=False),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('rejected_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('refunded_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_order_id', sa.Uuid(), nullable=False),
    sa.Column('order_detail_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['order_detail_id'], ['order_detail.id'], ),
    sa.ForeignKeyConstraint(['return_order_id'], ['return_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_item')
    op.drop_table('return_order')
    # ### end Alembic commands ###
