"""add index, constraint

Revision ID: c53d788963f0
Revises: 7cde958829a0
Create Date: 2026-05-26 15:35:38.198903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c53d788963f0'
down_revision: Union[str, None] = '7cde958829a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_address_user_deleted', 'address', ['user_id', 'deleted_at'], unique=False)
    op.create_index('ix_address_ward_id', 'address', ['ward_id'], unique=False)
    op.create_index('ix_cash_txn_performed_by', 'cash_transaction', ['performed_by'], unique=False)
    op.create_index('ix_cash_txn_type_category_date', 'cash_transaction', ['transaction_type', 'category', 'transaction_date'], unique=False)
    op.create_index('ix_evaluate_product_created', 'evaluate', ['product_id', 'created_at'], unique=False)
    op.create_index('ix_evaluate_product_rate', 'evaluate', ['product_id', 'rate'], unique=False)
    op.create_index('ix_evaluate_user_id', 'evaluate', ['user_id'], unique=False)
    op.create_index('ix_goods_receipt_po_status', 'goods_receipt', ['purchase_order_id', 'status'], unique=False)
    op.create_index('ix_goods_receipt_supplier_status', 'goods_receipt', ['supplier_id', 'status', 'receipt_date'], unique=False)
    op.create_index('ix_grd_goods_receipt_id', 'goods_receipt_detail', ['goods_receipt_id'], unique=False)
    op.create_index('ix_notification_recipient_read', 'notification', ['recipient_id', 'is_read', 'created_at'], unique=False)
    op.create_index('ix_notification_recipient_type', 'notification', ['recipient_type', 'recipient_id'], unique=False)
    op.create_index('ix_notification_return_order_id', 'notification', ['return_order_id'], unique=False)
    op.create_index('ix_order_code', 'order', ['code'], unique=False)
    op.create_index('ix_order_deleted_at', 'order', ['deleted_at'], unique=False)
    op.create_index('ix_order_payment_status', 'order', ['payment_status'], unique=False)
    op.create_index('ix_order_special_offer_id', 'order', ['special_offer_id'], unique=False)
    op.create_index('ix_order_status_created', 'order', ['status', 'created_at'], unique=False)
    op.create_index('ix_order_user_status', 'order', ['user_id', 'status'], unique=False)
    op.create_index('ix_order_detail_order_id', 'order_detail', ['order_id'], unique=False)
    op.create_index('ix_order_detail_product_variant', 'order_detail', ['product_id', 'product_variant_id'], unique=False)
    op.create_index('ix_payment_order_id', 'payment', ['order_id'], unique=False)
    op.create_index('ix_payment_status_created', 'payment', ['status', 'created_at'], unique=False)
    op.create_index('ix_payment_refund_payment_id', 'payment_refund', ['payment_id'], unique=False)
    op.create_index('ix_payment_refund_status', 'payment_refund', ['status', 'created_at'], unique=False)
    op.create_index('ix_product_brand_status', 'product', ['brand_id', 'status'], unique=False)
    op.create_index('ix_product_deleted_at', 'product', ['deleted_at'], unique=False)
    op.create_index('ix_product_special_offer_status', 'product', ['special_offer_id', 'status', 'deleted_at'], unique=False)
    op.create_index('ix_product_status_popularity', 'product', ['status', 'popularity_score'], unique=False)
    op.create_index('ix_product_status_rating', 'product', ['status', 'avg_rating'], unique=False)
    op.create_index('ix_variant_product_id', 'product_variant', ['product_id'], unique=False)
    op.create_index('ix_variant_sku_unique_not_deleted', 'product_variant', ['sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_po_payment_status', 'purchase_order', ['payment_status'], unique=False)
    op.create_index('ix_po_supplier_status', 'purchase_order', ['supplier_id', 'status', 'order_date'], unique=False)
    op.create_index('ix_po_detail_purchase_order_id', 'purchase_order_detail', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_return_po_id', 'purchase_return', ['purchase_order_id'], unique=False)
    op.create_index('ix_purchase_return_supplier_status', 'purchase_return', ['supplier_id', 'status', 'return_date'], unique=False)
    op.create_index('ix_prd_purchase_return_id', 'purchase_return_detail', ['purchase_return_id'], unique=False)
    op.create_index('ix_return_item_order_detail_id', 'return_item', ['order_detail_id'], unique=False)
    op.create_index('ix_return_item_return_order_id', 'return_item', ['return_order_id'], unique=False)
    op.create_index('ix_return_order_order_id', 'return_order', ['order_id'], unique=False)
    op.create_index('ix_return_order_status', 'return_order', ['status', 'created_at'], unique=False)
    op.create_index('ix_return_order_user', 'return_order', ['user_id', 'status'], unique=False)
    op.create_index('ix_special_offer_active_time', 'special_offer', ['start_time', 'end_time'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_special_offer_code_unique_not_deleted', 'special_offer', ['code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_stock_low_stock', 'stock', ['warehouse_id', 'available_quantity'], unique=False, postgresql_where=sa.text("status = 'low_stock'"))
    op.create_index('ix_stock_adj_item_adjustment_id', 'stock_adjustment_item', ['stock_adjustment_id'], unique=False)
    op.create_index('ix_stock_reservation_expires_active', 'stock_reservation', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_stock_reservation_reference', 'stock_reservation', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_stock_reservation_variant_status', 'stock_reservation', ['product_variant_id', 'status'], unique=False)
    op.create_index('ix_stock_txn_reference', 'stock_transaction', ['reference_type', 'reference_id'], unique=False)
    op.create_index('ix_stock_txn_warehouse_type_date', 'stock_transaction', ['warehouse_id', 'transaction_type', 'created_at'], unique=False)
    op.create_index('ix_supplier_name', 'supplier', ['name'], unique=False)
    op.create_index('ix_supplier_payment_po_id', 'supplier_payment', ['purchase_order_id'], unique=False)
    op.create_index('ix_supplier_payment_status_date', 'supplier_payment', ['status', 'payment_date'], unique=False)
    op.create_index('ix_supplier_payment_supplier_id', 'supplier_payment', ['supplier_id'], unique=False)
    op.create_index('ix_user_customer_status', 'user', ['is_customer', 'customer_status', 'deleted_at'], unique=False)
    op.create_index('ix_user_email_unique_not_deleted', 'user', ['email'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('ix_user_staff_status', 'user', ['is_staff', 'staff_status', 'deleted_at'], unique=False)
    op.create_foreign_key('fk_user_warehouse_id', 'user', 'warehouse', ['warehouse_id'], ['id'], use_alter=True)
    op.create_foreign_key('fk_warehouse_manager_id', 'warehouse', 'user', ['manager_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_warehouse_manager_id', 'warehouse', type_='foreignkey')
    op.drop_constraint('fk_user_warehouse_id', 'user', type_='foreignkey')
    op.drop_index('ix_user_staff_status', table_name='user')
    op.drop_index('ix_user_email_unique_not_deleted', table_name='user', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_user_customer_status', table_name='user')
    op.drop_index('ix_supplier_payment_supplier_id', table_name='supplier_payment')
    op.drop_index('ix_supplier_payment_status_date', table_name='supplier_payment')
    op.drop_index('ix_supplier_payment_po_id', table_name='supplier_payment')
    op.drop_index('ix_supplier_name', table_name='supplier')
    op.drop_index('ix_stock_txn_warehouse_type_date', table_name='stock_transaction')
    op.drop_index('ix_stock_txn_reference', table_name='stock_transaction')
    op.drop_index('ix_stock_reservation_variant_status', table_name='stock_reservation')
    op.drop_index('ix_stock_reservation_reference', table_name='stock_reservation')
    op.drop_index('ix_stock_reservation_expires_active', table_name='stock_reservation', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('ix_stock_adj_item_adjustment_id', table_name='stock_adjustment_item')
    op.drop_index('ix_stock_low_stock', table_name='stock', postgresql_where=sa.text("status = 'low_stock'"))
    op.drop_index('ix_special_offer_code_unique_not_deleted', table_name='special_offer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_special_offer_active_time', table_name='special_offer', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_return_order_user', table_name='return_order')
    op.drop_index('ix_return_order_status', table_name='return_order')
    op.drop_index('ix_return_order_order_id', table_name='return_order')
    op.drop_index('ix_return_item_return_order_id', table_name='return_item')
    op.drop_index('ix_return_item_order_detail_id', table_name='return_item')
    op.drop_index('ix_prd_purchase_return_id', table_name='purchase_return_detail')
    op.drop_index('ix_purchase_return_supplier_status', table_name='purchase_return')
    op.drop_index('ix_purchase_return_po_id', table_name='purchase_return')
    op.drop_index('ix_po_detail_purchase_order_id', table_name='purchase_order_detail')
    op.drop_index('ix_po_supplier_status', table_name='purchase_order')
    op.drop_index('ix_po_payment_status', table_name='purchase_order')
    op.drop_index('ix_variant_sku_unique_not_deleted', table_name='product_variant', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_variant_product_id', table_name='product_variant')
    op.drop_index('ix_product_status_rating', table_name='product')
    op.drop_index('ix_product_status_popularity', table_name='product')
    op.drop_index('ix_product_special_offer_status', table_name='product')
    op.drop_index('ix_product_deleted_at', table_name='product')
    op.drop_index('ix_product_brand_status', table_name='product')
    op.drop_index('ix_payment_refund_status', table_name='payment_refund')
    op.drop_index('ix_payment_refund_payment_id', table_name='payment_refund')
    op.drop_index('ix_payment_status_created', table_name='payment')
    op.drop_index('ix_payment_order_id', table_name='payment')
    op.drop_index('ix_order_detail_product_variant', table_name='order_detail')
    op.drop_index('ix_order_detail_order_id', table_name='order_detail')
    op.drop_index('ix_order_user_status', table_name='order')
    op.drop_index('ix_order_status_created', table_name='order')
    op.drop_index('ix_order_special_offer_id', table_name='order')
    op.drop_index('ix_order_payment_status', table_name='order')
    op.drop_index('ix_order_deleted_at', table_name='order')
    op.drop_index('ix_order_code', table_name='order')
    op.drop_index('ix_notification_return_order_id', table_name='notification')
    op.drop_index('ix_notification_recipient_type', table_name='notification')
    op.drop_index('ix_notification_recipient_read', table_name='notification')
    op.drop_index('ix_grd_goods_receipt_id', table_name='goods_receipt_detail')
    op.drop_index('ix_goods_receipt_supplier_status', table_name='goods_receipt')
    op.drop_index('ix_goods_receipt_po_status', table_name='goods_receipt')
    op.drop_index('ix_evaluate_user_id', table_name='evaluate')
    op.drop_index('ix_evaluate_product_rate', table_name='evaluate')
    op.drop_index('ix_evaluate_product_created', table_name='evaluate')
    op.drop_index('ix_cash_txn_type_category_date', table_name='cash_transaction')
    op.drop_index('ix_cash_txn_performed_by', table_name='cash_transaction')
    op.drop_index('ix_address_ward_id', table_name='address')
    op.drop_index('ix_address_user_deleted', table_name='address')
    # ### end Alembic commands ###
