"""add return order to notification

Revision ID: cb83dbe3665c
Revises: ac3b380cd8e7
Create Date: 2025-09-15 09:12:24.935065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cb83dbe3665c'
down_revision: Union[str, None] = 'ac3b380cd8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('return_order_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'notification', 'return_order', ['return_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'return_order_id')
    # ### end Alembic commands ###
