"""add size table

Revision ID: cbff3ed53614
Revises: 10300b795bd0
Create Date: 2025-08-16 10:04:10.857032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cbff3ed53614'
down_revision: Union[str, None] = '10300b795bd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.Column('name', sa.VARCHAR(), nullable=False),
                    sa.Column('type', sa.VARCHAR(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('categories', sa.Column('type_size', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
    op.execute("""
            INSERT INTO size (id, name, type) VALUES
                (gen_random_uuid(), 'S', 'clothing'),
                (gen_random_uuid(), 'M', 'clothing'),
                (gen_random_uuid(), 'L', 'clothing'),
                (gen_random_uuid(), 'XL', 'clothing'),
                (gen_random_uuid(), 'XXL', 'clothing'),
                (gen_random_uuid(), '33', 'shoe'),
                (gen_random_uuid(), '34', 'shoe'),
                (gen_random_uuid(), '35', 'shoe'),
                (gen_random_uuid(), '36', 'shoe'),
                (gen_random_uuid(), '37', 'shoe'),
                (gen_random_uuid(), '38', 'shoe'),
                (gen_random_uuid(), '39', 'shoe'),
                (gen_random_uuid(), '40', 'shoe'),
                (gen_random_uuid(), '41', 'shoe'),
                (gen_random_uuid(), '42', 'shoe'),
                (gen_random_uuid(), '43', 'shoe'),
                (gen_random_uuid(), '44', 'shoe'),
                (gen_random_uuid(), '45', 'shoe'),
                (gen_random_uuid(), 'S', 'hat'),
                (gen_random_uuid(), 'M', 'hat'),
                (gen_random_uuid(), 'L', 'hat'),
                (gen_random_uuid(), 'XL', 'hat'),
                (gen_random_uuid(), 'XXL', 'hat'),
                (gen_random_uuid(), '7', 'accessory'),
                (gen_random_uuid(), '8', 'accessory'),
                (gen_random_uuid(), '9', 'accessory'),
                (gen_random_uuid(), '10', 'accessory'),
                (gen_random_uuid(), '11', 'accessory'),
                (gen_random_uuid(), '12', 'accessory'),
                (gen_random_uuid(), '13', 'accessory'),
                (gen_random_uuid(), '14', 'accessory'),
                (gen_random_uuid(), '15', 'accessory'),
                (gen_random_uuid(), '16', 'accessory'),
                (gen_random_uuid(), '17', 'accessory'),
                (gen_random_uuid(), '18', 'accessory'),
                (gen_random_uuid(), '19', 'accessory'),
                (gen_random_uuid(), '20', 'accessory'),
                (gen_random_uuid(), '21', 'accessory'),
                (gen_random_uuid(), '22', 'accessory'),
                (gen_random_uuid(), '40', 'accessory'),
                (gen_random_uuid(), '41', 'accessory'),
                (gen_random_uuid(), '42', 'accessory'),
                (gen_random_uuid(), '43', 'accessory'),
                (gen_random_uuid(), '44', 'accessory'),
                (gen_random_uuid(), '45', 'accessory'),
                (gen_random_uuid(), 'Free', 'accessory')
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'type_size')
    op.drop_table('size')
    # ### end Alembic commands ###
