"""update color table and product variant

Revision ID: cffc7040e573
Revises: d36f0eb57430
Create Date: 2025-08-12 10:04:26.698410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cffc7040e573'
down_revision: Union[str, None] = 'd36f0eb57430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('code', sa.VARCHAR(), nullable=False))
    op.add_column('product_variant', sa.Column('color_id', sa.Uuid(), nullable=True))
    op.add_column('product_variant', sa.Column('color_name', sa.VARCHAR(), nullable=True))
    op.add_column('product_variant', sa.Column('color_code', sa.VARCHAR(), nullable=True))
    op.create_foreign_key(None, 'product_variant', 'color', ['color_id'], ['id'])
    op.drop_column('product_variant', 'color')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variant', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product_variant', type_='foreignkey')
    op.drop_column('product_variant', 'color_code')
    op.drop_column('product_variant', 'color_name')
    op.drop_column('product_variant', 'color_id')
    op.drop_column('color', 'code')
    # ### end Alembic commands ###
