"""add table Notification

Revision ID: d0e6888859c2
Revises: 3bba1b132478
Create Date: 2025-09-10 13:04:51.353492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0e6888859c2'
down_revision: Union[str, None] = '3bba1b132478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.VARCHAR(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('sender_type', sa.VARCHAR(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default='false', nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
