"""add additional to evaluate

Revision ID: d36f0eb57430
Revises: 3ac161248c94
Create Date: 2025-07-25 14:23:34.596289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd36f0eb57430'
down_revision: Union[str, None] = '3ac161248c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('additional_comment', sa.VARCHAR(), nullable=True))
    op.add_column('evaluate', sa.Column('additional_image', sa.VARCHAR(), nullable=True))
    op.add_column('evaluate', sa.Column('additional_created_at', postgresql.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluate', 'additional_created_at')
    op.drop_column('evaluate', 'additional_image')
    op.drop_column('evaluate', 'additional_comment')
    # ### end Alembic commands ###
