"""update all inventory db 3

Revision ID: d7a344f6c83b
Revises: d94b78dcb5ef
Create Date: 2025-10-09 10:49:44.916394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7a344f6c83b'
down_revision: Union[str, None] = 'd94b78dcb5ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_return',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('return_number', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_order_id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_id', sa.Uuid(), nullable=True),
    sa.Column('supplier_id', sa.Uuid(), nullable=False),
    sa.Column('warehouse_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.VARCHAR(), server_default='draft', nullable=False),
    sa.Column('return_type', sa.VARCHAR(), server_default='return_to_supplier', nullable=False),
    sa.Column('return_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('shipped_date', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('total_return_amount', sa.INTEGER(), nullable=False),
    sa.Column('refund_amount', sa.INTEGER(), nullable=False),
    sa.Column('refunded_amount', sa.INTEGER(), nullable=False),
    sa.Column('return_reason', sa.TEXT(), nullable=False),
    sa.Column('delivery_note_number', sa.VARCHAR(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('return_number')
    )
    op.create_table('purchase_return_detail',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('purchase_return_id', sa.Uuid(), nullable=False),
    sa.Column('product_variant_id', sa.Uuid(), nullable=False),
    sa.Column('goods_receipt_detail_id', sa.Uuid(), nullable=True),
    sa.Column('return_quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), nullable=False),
    sa.Column('total_cost', sa.INTEGER(), nullable=False),
    sa.Column('condition', sa.VARCHAR(), nullable=True),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['goods_receipt_detail_id'], ['goods_receipt_detail.id'], ),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], ),
    sa.ForeignKeyConstraint(['purchase_return_id'], ['purchase_return.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('goods_receipt', 'quality_check_passed')
    op.drop_column('goods_receipt_detail', 'quality_status')
    op.drop_column('purchase_order', 'payment_terms')
    op.drop_column('supplier', 'payment_terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('payment_terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('purchase_order', sa.Column('payment_terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('goods_receipt_detail', sa.Column('quality_status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.add_column('goods_receipt', sa.Column('quality_check_passed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('purchase_return_detail')
    op.drop_table('purchase_return')
    # ### end Alembic commands ###
