"""update all inventory db

Revision ID: d94b78dcb5ef
Revises: 8550bba40a3b
Create Date: 2025-10-08 19:23:10.556494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd94b78dcb5ef'
down_revision: Union[str, None] = '8550bba40a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partial_delivery_detail')
    op.drop_table('penalty_record')
    op.drop_table('partial_delivery_schedule')
    op.drop_column('goods_receipt', 'delivery_batch_number')
    op.drop_column('goods_receipt', 'is_partial_delivery_batch')
    op.add_column('purchase_order', sa.Column('payment_terms', sa.VARCHAR(), nullable=True))
    op.drop_column('purchase_order', 'extended_payment_due_date')
    op.drop_column('purchase_order', 'total_delivery_batches')
    op.drop_column('purchase_order', 'completed_delivery_batches')
    op.drop_column('purchase_order', 'is_partial_delivery')
    op.drop_column('purchase_order', 'original_payment_due_date')
    op.drop_column('purchase_order', 'applied_terms')
    op.add_column('supplier', sa.Column('payment_terms', sa.VARCHAR(), nullable=True))
    op.add_column('supplier', sa.Column('credit_limit', sa.INTEGER(), nullable=True))
    op.drop_column('supplier', 'terms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('terms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('supplier', 'credit_limit')
    op.drop_column('supplier', 'payment_terms')
    op.add_column('purchase_order', sa.Column('applied_terms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('purchase_order', sa.Column('original_payment_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('purchase_order', sa.Column('is_partial_delivery', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('purchase_order', sa.Column('completed_delivery_batches', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('purchase_order', sa.Column('total_delivery_batches', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('purchase_order', sa.Column('extended_payment_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('purchase_order', 'payment_terms')
    op.add_column('goods_receipt', sa.Column('is_partial_delivery_batch', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('goods_receipt', sa.Column('delivery_batch_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_table('partial_delivery_schedule',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('delivery_batch_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposed_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposed_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proposed_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('proposed_payment_extension_days', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('actual_delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('actual_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('actual_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('approved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], name='partial_delivery_schedule_approved_by_fkey'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], name='partial_delivery_schedule_goods_receipt_id_fkey'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name='partial_delivery_schedule_purchase_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='partial_delivery_schedule_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('penalty_record',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('penalty_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('partial_delivery_schedule_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('supplier_payment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('violation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('violated_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('violation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expected_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('actual_value', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difference_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difference_unit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('evidence_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), server_default=sa.text("'recorded'::character varying"), autoincrement=False, nullable=False),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('agreed_compensation_amount', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('resolved_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('penalty_record_created_by_fkey')),
    sa.ForeignKeyConstraint(['partial_delivery_schedule_id'], ['partial_delivery_schedule.id'], name=op.f('penalty_record_partial_delivery_schedule_id_fkey')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], name=op.f('penalty_record_purchase_order_id_fkey')),
    sa.ForeignKeyConstraint(['resolved_by'], ['user.id'], name=op.f('penalty_record_resolved_by_fkey')),
    sa.ForeignKeyConstraint(['supplier_payment_id'], ['supplier_payment.id'], name=op.f('penalty_record_supplier_payment_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('penalty_record_pkey')),
    sa.UniqueConstraint('penalty_code', name=op.f('penalty_record_penalty_code_key'))
    )
    op.create_table('partial_delivery_detail',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_variant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('po_detail_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposed_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('actual_quantity', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_snapshot', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_detail_id'], ['purchase_order_detail.id'], name=op.f('partial_delivery_detail_po_detail_id_fkey')),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variant.id'], name=op.f('partial_delivery_detail_product_variant_id_fkey')),
    sa.ForeignKeyConstraint(['schedule_id'], ['partial_delivery_schedule.id'], name=op.f('partial_delivery_detail_schedule_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('partial_delivery_detail_pkey'))
    )
    # ### end Alembic commands ###
