"""add attempt_count to PaymentRefund

Revision ID: de2a65f33cd3
Revises: 0b3669fba714
Create Date: 2025-09-17 16:11:42.675853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'de2a65f33cd3'
down_revision: Union[str, None] = '0b3669fba714'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_refund', sa.Column('attempt_count', sa.INTEGER(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_refund', 'attempt_count')
    # ### end Alembic commands ###
