"""Add slug to tables

Revision ID: df64eefe4df0
Revises: 6b1e5277eb75
Create Date: 2025-09-21 10:05:04.723473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df64eefe4df0'
down_revision: Union[str, None] = '6b1e5277eb75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('slug', sa.VARCHAR(), nullable=False))
    op.add_column('brand', sa.Column('logo', sa.VARCHAR(), nullable=True))
    op.add_column('brand', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False))
    op.create_unique_constraint(None, 'brand', ['slug'])
    op.add_column('categories', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_unique_constraint(None, 'categories', ['slug'])
    op.add_column('material', sa.Column('slug', sa.VARCHAR(), nullable=False))
    op.add_column('material', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False))
    op.create_unique_constraint(None, 'material', ['slug'])
    op.add_column('product', sa.Column('slug', sa.VARCHAR(), nullable=True))
    op.create_unique_constraint(None, 'product', ['slug'])
    op.add_column('tag', sa.Column('slug', sa.VARCHAR(), nullable=False))
    op.add_column('tag', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False))
    op.create_unique_constraint(None, 'tag', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_column('tag', 'is_active')
    op.drop_column('tag', 'slug')
    op.drop_constraint(None, 'product', type_='unique')
    op.drop_column('product', 'slug')
    op.drop_constraint(None, 'material', type_='unique')
    op.drop_column('material', 'is_active')
    op.drop_column('material', 'slug')
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'slug')
    op.drop_constraint(None, 'brand', type_='unique')
    op.drop_column('brand', 'is_active')
    op.drop_column('brand', 'logo')
    op.drop_column('brand', 'slug')
    # ### end Alembic commands ###
