"""update image and seller_reply

Revision ID: e0e13b23160a
Revises: f28fd4354b44
Create Date: 2025-08-27 09:31:09.815195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e13b23160a'
down_revision: Union[str, None] = 'f28fd4354b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluate', sa.Column('seller_reply', sa.TEXT(), nullable=True))
    op.add_column('evaluate', sa.Column('seller_reply_at', postgresql.TIMESTAMP(), nullable=True))
    op.alter_column('product_variant', 'image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_variant', 'image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('evaluate', 'seller_reply_at')
    op.drop_column('evaluate', 'seller_reply')
    # ### end Alembic commands ###
