"""update_categories_image

Revision ID: e2616f79d24b
Revises: ff339e7bf3fa
Create Date: 2025-06-24 11:58:42.746495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2616f79d24b'
down_revision: Union[str, None] = 'ff339e7bf3fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image', sa.VARCHAR(), nullable=False))
    op.drop_column('categories', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('images', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('categories', 'image')
    # ### end Alembic commands ###
