"""update table UserSpecialOffer

Revision ID: e9463589be13
Revises: 9b389cd1a8f2
Create Date: 2025-09-09 09:02:37.667203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9463589be13'
down_revision: Union[str, None] = '9b389cd1a8f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_special_offer'), 'user_special_offer', type_='unique')
    op.drop_column('user_special_offer', 'deleted_at')
    op.drop_column('user_special_offer', 'is_used')
    op.drop_column('user_special_offer', 'created_at')
    op.drop_column('user_special_offer', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_special_offer', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user_special_offer', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False))
    op.add_column('user_special_offer', sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_special_offer', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_user_special_offer'), 'user_special_offer', ['user_id', 'special_offer_id'])
    # ### end Alembic commands ###
