"""add OTPVerificationAttempt model 2

Revision ID: e9675d85835c
Revises: f72069123e69
Create Date: 2025-11-10 10:59:21.962717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9675d85835c'
down_revision: Union[str, None] = 'f72069123e69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verification_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), nullable=False),
    sa.Column('is_successful', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_ip_attempted_at', 'otp_verification_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index('idx_otp_user_id_attempted_at', 'otp_verification_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_otp_verification_attempts_attempted_at'), 'otp_verification_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_otp_verification_attempts_user_id'), 'otp_verification_attempts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_verification_attempts_user_id'), table_name='otp_verification_attempts')
    op.drop_index(op.f('ix_otp_verification_attempts_attempted_at'), table_name='otp_verification_attempts')
    op.drop_index('idx_otp_user_id_attempted_at', table_name='otp_verification_attempts')
    op.drop_index('idx_otp_ip_attempted_at', table_name='otp_verification_attempts')
    op.drop_table('otp_verification_attempts')
    # ### end Alembic commands ###
