"""refactor table PurchaseReturn

Revision ID: ea5bc5731ea7
Revises: 242af0411b4e
Create Date: 2026-01-12 14:00:19.361016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea5bc5731ea7'
down_revision: Union[str, None] = '242af0411b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_return', sa.Column('deleted_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('user', 'expires_at')
    op.drop_column('user', 'otp_hash')
    op.drop_column('user', 'otp_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('otp_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('otp_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('purchase_return', 'deleted_at')
    # ### end Alembic commands ###
