"""update type_size for categories

Revision ID: f26dffccc95f
Revises: 932d8ac1870c
Create Date: 2025-08-18 10:00:34.194396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f26dffccc95f'
down_revision: Union[str, None] = '932d8ac1870c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type_size',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type_size',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
