"""add image to variant

Revision ID: f28fd4354b44
Revises: 31d4a71cfff3
Create Date: 2025-08-26 09:32:23.354698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f28fd4354b44'
down_revision: Union[str, None] = '31d4a71cfff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_variant', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_variant', 'image')
    # ### end Alembic commands ###
