"""add Province and Ward model

Revision ID: fea596419438
Revises: e9675d85835c
Create Date: 2025-11-12 21:11:26.191372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fea596419438'
down_revision: Union[str, None] = 'e9675d85835c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code_name', sa.VARCHAR(), nullable=False),
    sa.Column('division_type', sa.VARCHAR(), nullable=False),
    sa.Column('phone_code', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_name')
    )
    op.create_table('ward',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('code_name', sa.VARCHAR(), nullable=False),
    sa.Column('short_code_name', sa.VARCHAR(), nullable=False),
    sa.Column('division_type', sa.VARCHAR(), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_code_name'), 'ward', ['code_name'], unique=False)
    op.add_column('address', sa.Column('ward_id', sa.Uuid(), nullable=False))
    op.add_column('address', sa.Column('province_id', sa.Uuid(), nullable=False))
    op.alter_column('address', 'district',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'address', 'province', ['province_id'], ['id'])
    op.create_foreign_key(None, 'address', 'ward', ['ward_id'], ['id'])
    op.drop_column('address', 'ward')
    op.drop_column('address', 'street')
    op.drop_column('address', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('address', sa.Column('ward', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.alter_column('address', 'district',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('address', 'province_id')
    op.drop_column('address', 'ward_id')
    op.drop_index(op.f('ix_ward_code_name'), table_name='ward')
    op.drop_table('ward')
    op.drop_table('province')
    # ### end Alembic commands ###
